version: '3.9'

services:
  mysql:
    image: mysql
    container_name: dev-db
    ports:
      - "3306:3306"
    environment:
      - TZ=+09:00
      - MYSQL_DATABASE=dev-db
      - MYSQL_USER=teamonandoff
      - MYSQL_PASSWORD=p@ssword
      - MYSQL_ROOT_PASSWORD=p@ssword

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"