name: prod branch auto ci process script

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_PROD_IP }}
          username: ${{ secrets.REMOTE_PROD_USER }}
          password: ${{ secrets.REMOTE_PROD_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/Server-V2
            git pull origin prod
            npm ci
            npm run build
            pm2 restart dist/main.js